# Dependencies
markdown:            kramdown
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  use_coderay:    false

pygments:         true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Parsed Corpora Wiki
tagline:             ''
description:         'A wiki for information on (Historical) Parsed Corpora'
url:                 http://parsedcorpora.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Hezekiah Akiva Bacovcin
  url:               https://www.ling.upenn.edu/~bacovcin
  email:             bacovcin@ling.upenn.edu

# Custom vars
version:             1.0.0

github:
  repo:           https://github.com/parsedcorpora/parsedcorpora.github.io

prose:
  ignore:
    - /\..*
    - /_config.yml
    - /atom.xml
    - /LICENSE.md
    - /_layouts
    - /_includes
    - /public
    - /blog
    - /README.md
    - /CNAME
    - /404.html
    - /.editorconfig
    - /.gitignore
    - /.gitmodules
  metadata:
    "":
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
